// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxnrdmhgyohyxzxhwaji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bnJkbWhneW9oeXh6eGh3YWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTY0MjksImV4cCI6MjA2MTk3MjQyOX0.M2FCttHldMcZfl7dTLb_5noi3-f2AqiTrLNw6UCsA8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);